#! /usr/bin/env python
#
# This runs the L1B Geo process.
from geocal import *
from ecostress import *
import os

version = "1.0"
usage='''Usage:
  l1b_geo_process [options] <run_config>
  l1b_geo_process -h | --help
  l1b_geo_process -v | --version

This runs the L1B Geo process.

Options:
  -h --help         
       Print this message

  --number-line=d
       Number of lines to process. Normally you process the whole scene, but
       can be useful for testing to process only a subset. [default: -1]

  -v --version      
       Print program version
'''

args = docopt_simple(usage, version=version)

# Can use this to wait a short time so we can attach strace to this
# process, useful to find all the files that we are accessing.
if(False):
    print "Waiting a short time"
    import time
    time.sleep(20)

# Explicitly list input file
config = RunConfig(args.run_config)

datum = config["StaticAncillaryFileGroup", "Datum"]
srtm_dir = config["StaticAncillaryFileGroup", "StrmDir"]
spice_data = config["StaticAncillaryFileGroup", "SpiceData"]
cam = read_shelve(config["StaticAncillaryFileGroup", "Camera"])
ncpu = int(config["Process", "NumberCpu"])
orb = read_shelve(config["InputFileGroup", "L1A_RAW_ATT"])
tt = read_shelve(config["InputFileGroup", "L1B_RAD"])
ofile = config["ProductGroup", "OutputFile"]

# Spice directory passed down as an environment variable
os.environ["SPICEDATA"] = spice_data

# Create IGC
band = 0
ipi = Ipi(orb, cam, band, tt.min_time, tt.max_time, tt)
# Create DEM. False here says it ok for SrtmDem to not have tile. This 
# gives support for data that is over the ocean.
dem = SrtmDem(srtm_dir,False, DatumGeoid96(datum))
igc = IpiImageGroundConnection(ipi, dem, None)

# Generate output
l1bgeo = L1bGeoGenerate(igc, ofile, number_line = args.number_line)
pool = Pool(ncpu)
l1bgeo.run(pool)

