#! /usr/bin/env python
#
# This projects L1B geo data
import geocal
import ecostress
import os
import subprocess

version = "1.0"
usage='''Usage:
  l1b_orthobase [options] <input_file> <output_file>
  l1b_orthobase -h | --help
  l1b_orthobase -v | --version

This create an output image file containing the orthobase data covering the
given input file.
Options:
  -h --help         
       Print this message

  --erdas
       In addition to producing vicar format, convert the output to erdas
       imagine file.

  --landsat-band=d
       Landsat band to match to. For band 6, we have both low and high gain.
       Enter this as 61 and 62. -1 means use the value found in the
       configuration file [default: 5]

  -v --version      
       Print program version
'''

args = geocal.docopt_simple(usage, version=version)

if(os.path.exists("/project/ancillary/LANDSAT")):
    # eco-scf location
    ortho_base = geocal.Landsat7Global("/project/ancillary/LANDSAT",
                          ecostress.band_to_landsat_band(args.landsat_band))
else:
    # pistol location
    ortho_base = geocal.Landsat7Global("/raid22",
                          ecostress.band_to_landsat_band(args.landsat_band))

mi = geocal.GdalRasterImage(args.input_file).map_info
ortho_base.create_subset_file(args.output_file, "VICAR",
                              Desired_map_info = mi,
                              Translate_arg = "-ot Int16")
if(args.erdas):
    cmd = ["gdal_to_erdas", args.output_file,
                os.path.splitext(args.output_file)[0] + "_erdas.img"]
    subprocess.run(cmd)


