#! /usr/bin/env python
#
# Create a KMZ file giving a picture of the MAP data
import geocal
import glob
import os

version = "1.0"
usage='''Usage:
  map_index [options] <directory>
  map_index -h | --help
  map_index -v | --version

Generate a simple HTML index of the KMZ/thumbnail contents of a directory.

Options:
  -h --help         
       Print this message

  -v --version      
       Print program version
'''

args = geocal.docopt_simple(usage, version=version)

fh = open("%s/index.html" % args.directory, "w")
head='''<!DOCTYPE html>
<html>
  <head>
    <title>ECOSTRESS Data</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>

  <div class="container">

    <table class="table table-striped">
      <thead>
	<tr>
	  <th scope="col">Orbit</th>
	  <th scope="col">Scene</th>
	  <th scope="col">Thumbnail</th>
	  <th scope="col">KMZ</th>
	</tr>
      </thead>
      <tbody>
'''
tail='''      </tbody>
  </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>
'''

def row(fname_in):
    '''Print a row that describes the given fname'''
    fname = os.path.basename(fname_in)
    fdata = fname.split("_")
    orb = fdata[3]
    scene = fdata[4]
    tfile = os.path.splitext(fname)[0] + "_thumbnail.jpg"
    print('''	<tr>
	  <td>%s</td>
	  <td>%s</td>
	  <td><img src="%s"></td>
	  <td><a type="application/vnd.google-earth.kmz" href="%s">KMZ</a></td>
	</tr>''' % (orb, scene, tfile, fname), file=fh)

print(head, file=fh)
for fname in sorted(glob.glob("%s/ECOSTRESS_L1B_MAP_*.kmz" % args.directory)):
    row(fname)
print(tail, file=fh)
