#! /usr/bin/env python
#
# This runs the L1A Raw process.

from geocal import *
from ecostress import *
import os
import re

# Get version information, in the top directory
import sys
sys.path.append(os.path.dirname(os.path.abspath(sys.path[0])))
from ecostress_version import *

version = "1.0"
usage='''Usage:
  l1a_raw_process [options] <run_config>
  l1a_raw_process [options] <l0b> <scene_file> <osp_dir> <prod_dir>
  l1a_raw_process -h | --help
  l1a_raw_process -v | --version

This runs the L1A Raw process.

Options:
  -h --help         
       Print this message

  -v --version      
       Print program version
'''

args = docopt_simple(usage, version=version)

# Can use this to wait a short time so we can attach strace to this
# process, useful to find all the files that we are accessing.
if(False):
    print("Waiting a short time")
    import time
    time.sleep(20)

# Explicitly list input file
if(args.run_config) :
    config = RunConfig(args.run_config)
    l0b = os.path.abspath(config["InputFileGroup", "L0B"])
    scene_file = os.path.abspath(config["StaticAncillaryFileGroup", "Scene"])
    osp_dir = os.path.abspath(config["StaticAncillaryFileGroup", "L1_OSP_DIR"])
    prod_dir = os.path.abspath(config["ProductPathGroup", "ProductPath"])
    shortname =  config["ProductPathGroup","ShortName"]
    file_version = config["ProductPathGroup", "ProductCounter"]
else:
    l0b = os.path.abspath(args.l0b)
    scene_file = os.path.abspath(args.scene_file)
    osp_dir = os.path.abspath(args.osp_dir)
    prod_dir = os.path.abspath(args.prod_dir)
    shortname = "L1a_Raw"
    file_version = "01"

print("L1A_RAW_PROCESS L0B=%s SCENE_FILE=%s PROD_DIR=%s OSP_DIR=%s SHORT=%s" % (l0b, scene_file, prod_dir, osp_dir, shortname ) )

makedirs_p(prod_dir)
os.chdir(prod_dir)

l1arawpix = L1aRawPixGenerate(l0b, osp_dir, scene_file,
                              build_id = build_id,
                              pge_version = pge_version["l1a_raw"],
                              build_version = build_version,
                              file_version = file_version)
l1arawpix.run()

