l1b1_sim_%.img:
	write_image --verbose --process-number-line=100 --process-number-sample=100 test_data.db:igc_simulated_$* $@

all: l1b1_sim_p1_b1.img l1b1_sim_p1_b2.img l1b1_sim_p1_b3.img l1b1_sim_p1_b4.img \
     l1b1_sim_p1_b5.img l1b1_sim_p1_b6.img
