# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _ecostress_time_table

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _ecostress_time_table.SWIG_PyInstanceMethod_New
_swig_new_static_method = _ecostress_time_table.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _ecostress_time_table.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ecostress_time_table.delete_SwigPyIterator
    value = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_value)
    incr = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_copy)
    next = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_ecostress_time_table.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ecostress_time_table:
_ecostress_time_table.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _ecostress_time_table.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.time_table
import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_time
class EcostressTimeTable(geocal_swig.time_table.TimeTable):
    r"""

    This is the ecostress time table.

    The table is different before and after we do the 2 line averaging in
    L1B_CAL, we indicate this by "averaging_done" set to true, which
    means each scan is treated as 128 lines rather than 256.

    Note that only the image coordinates changes from 128/256 per scan
    index. The FrameCoordinate are in terms of the actual Ecostress
    camera, so there is always 256 frame coordinate lines in a scan.

    C++ includes: ecostress_time_table.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        EcostressTimeTable::EcostressTimeTable(const std::string &Fname, bool Averaging_done, double
        Mirror_rpm=25.4, double Frame_time=0.0000321875, double Toffset=0)
        Create a time table by reading the input file.

        The file should be a L1A_PIX or a L1B_RAD file.

        This variation lets you set the Averaging_done explicitly. Normally we
        just set Averaging_done for L1B_RAD and have it false for L1A_PIX. But
        for testing purposes it can be useful to read one dataset and then
        pretend it for a different averaging mode. 
        """
        _ecostress_time_table.EcostressTimeTable_swiginit(self, _ecostress_time_table.new_EcostressTimeTable(*args))
    scan_index_to_line = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable_scan_index_to_line)
    line_to_scan_index = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable_line_to_scan_index)
    close_to_scan_edge = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable_close_to_scan_edge)
    _v_averaging_done = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_averaging_done)

    @property
    def averaging_done(self):
        return self._v_averaging_done()

    _v_number_line_scan = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_number_line_scan)

    @property
    def number_line_scan(self):
        return self._v_number_line_scan()

    _v_number_good_scan = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_number_good_scan)

    @property
    def number_good_scan(self):
        return self._v_number_good_scan()

    _v_number_scan = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_number_scan)

    @property
    def number_scan(self):
        return self._v_number_scan()

    _v_mirror_rpm = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_mirror_rpm)

    @property
    def mirror_rpm(self):
        return self._v_mirror_rpm()

    _v_nominal_scan_time = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_nominal_scan_time)

    @property
    def nominal_scan_time(self):
        return self._v_nominal_scan_time()

    _v_frame_time = _swig_new_instance_method(_ecostress_time_table.EcostressTimeTable__v_frame_time)

    @property
    def frame_time(self):
        return self._v_frame_time()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _ecostress_time_table.delete_EcostressTimeTable

# Register EcostressTimeTable in _ecostress_time_table:
_ecostress_time_table.EcostressTimeTable_swigregister(EcostressTimeTable)

__all__ = ["EcostressTimeTable"]


