# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _ecostress_dqi

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _ecostress_dqi.SWIG_PyInstanceMethod_New
_swig_new_static_method = _ecostress_dqi.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _ecostress_dqi.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ecostress_dqi.delete_SwigPyIterator
    value = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_value)
    incr = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_copy)
    next = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_ecostress_dqi.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ecostress_dqi:
_ecostress_dqi.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _ecostress_dqi.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

DQI_GOOD = _ecostress_dqi.DQI_GOOD
DQI_INTERPOLATED = _ecostress_dqi.DQI_INTERPOLATED
DQI_STRIPE_NOT_INTERPOLATED = _ecostress_dqi.DQI_STRIPE_NOT_INTERPOLATED
DQI_BAD_OR_MISSING = _ecostress_dqi.DQI_BAD_OR_MISSING
DQI_NOT_SEEN = _ecostress_dqi.DQI_NOT_SEEN
FILL_VALUE_BAD_OR_MISSING = _ecostress_dqi.FILL_VALUE_BAD_OR_MISSING
FILL_VALUE_STRIPED = _ecostress_dqi.FILL_VALUE_STRIPED
FILL_VALUE_NOT_SEEN = _ecostress_dqi.FILL_VALUE_NOT_SEEN

__all__ = ["DQI_GOOD","DQI_INTERPOLATED","DQI_STRIPE_NOT_INTERPOLATED","DQI_BAD_OR_MISSING","DQI_NOT_SEEN","FILL_VALUE_BAD_OR_MISSING","FILL_VALUE_STRIPED","FILL_VALUE_NOT_SEEN","fill_value_threshold"]


cvar = _ecostress_dqi.cvar
fill_value_threshold = cvar.fill_value_threshold

