# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _ecostress_image_ground_connection_subset

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _ecostress_image_ground_connection_subset.SWIG_PyInstanceMethod_New
_swig_new_static_method = _ecostress_image_ground_connection_subset.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _ecostress_image_ground_connection_subset.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ecostress_image_ground_connection_subset.delete_SwigPyIterator
    value = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_value)
    incr = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_copy)
    next = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_ecostress_image_ground_connection_subset.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ecostress_image_ground_connection_subset:
_ecostress_image_ground_connection_subset.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _ecostress_image_ground_connection_subset.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.image_ground_connection
import geocal_swig.generic_object
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
import geocal_swig.time_table
import geocal_swig.observer
class EcostressImageGroundConnection(geocal_swig.image_ground_connection.ImageGroundConnection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    REF_BAND = _ecostress_image_ground_connection_subset.EcostressImageGroundConnection_REF_BAND

    def __init__(self, *args):
        _ecostress_image_ground_connection_subset.EcostressImageGroundConnection_swiginit(self, _ecostress_image_ground_connection_subset.new_EcostressImageGroundConnection(*args))
    orbit_data = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection_orbit_data)
    image_coordinate_scan_index = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection_image_coordinate_scan_index)
    scan_index_to_line = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection_scan_index_to_line)
    _v_crosses_dateline = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_crosses_dateline)

    @property
    def crosses_dateline(self):
        return self._v_crosses_dateline()

    _v_number_line_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_number_line_scan)

    @property
    def number_line_scan(self):
        return self._v_number_line_scan()

    _v_number_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_number_scan)

    @property
    def number_scan(self):
        return self._v_number_scan()

    _v_number_good_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_number_good_scan)

    @property
    def number_good_scan(self):
        return self._v_number_good_scan()

    _v_band = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_band)

    @property
    def band(self):
        return self._v_band()

    @band.setter
    def band(self, value):
      self._v_band(value)

    _v_resolution = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_resolution)

    @property
    def resolution(self):
        return self._v_resolution()

    @resolution.setter
    def resolution(self, value):
      self._v_resolution(value)

    _v_max_height = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_max_height)

    @property
    def max_height(self):
        return self._v_max_height()

    @max_height.setter
    def max_height(self, value):
      self._v_max_height(value)

    _v_orbit = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_orbit)

    @property
    def orbit(self):
        return self._v_orbit()

    @orbit.setter
    def orbit(self, value):
      self._v_orbit(value)

    _v_time_table = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_time_table)

    @property
    def time_table(self):
        return self._v_time_table()

    @time_table.setter
    def time_table(self, value):
      self._v_time_table(value)

    _v_camera = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_camera)

    @property
    def camera(self):
        return self._v_camera()

    @camera.setter
    def camera(self, value):
      self._v_camera(value)

    _v_scan_mirror = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnection__v_scan_mirror)

    @property
    def scan_mirror(self):
        return self._v_scan_mirror()

    @scan_mirror.setter
    def scan_mirror(self, value):
      self._v_scan_mirror(value)


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _ecostress_image_ground_connection_subset.delete_EcostressImageGroundConnection

# Register EcostressImageGroundConnection in _ecostress_image_ground_connection_subset:
_ecostress_image_ground_connection_subset.EcostressImageGroundConnection_swigregister(EcostressImageGroundConnection)

__all__ = ["EcostressImageGroundConnection"]

class EcostressTimeTable(geocal_swig.time_table.TimeTable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ecostress_image_ground_connection_subset.EcostressTimeTable_swiginit(self, _ecostress_image_ground_connection_subset.new_EcostressTimeTable(*args))
    scan_index_to_line = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable_scan_index_to_line)
    line_to_scan_index = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable_line_to_scan_index)
    close_to_scan_edge = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable_close_to_scan_edge)
    _v_averaging_done = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_averaging_done)

    @property
    def averaging_done(self):
        return self._v_averaging_done()

    _v_number_line_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_number_line_scan)

    @property
    def number_line_scan(self):
        return self._v_number_line_scan()

    _v_number_good_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_number_good_scan)

    @property
    def number_good_scan(self):
        return self._v_number_good_scan()

    _v_number_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_number_scan)

    @property
    def number_scan(self):
        return self._v_number_scan()

    _v_mirror_rpm = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_mirror_rpm)

    @property
    def mirror_rpm(self):
        return self._v_mirror_rpm()

    _v_nominal_scan_time = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_nominal_scan_time)

    @property
    def nominal_scan_time(self):
        return self._v_nominal_scan_time()

    _v_frame_time = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_frame_time)

    @property
    def frame_time(self):
        return self._v_frame_time()

    _v_tstart_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTable__v_tstart_scan)

    @property
    def tstart_scan(self):
        return self._v_tstart_scan()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _ecostress_image_ground_connection_subset.delete_EcostressTimeTable

# Register EcostressTimeTable in _ecostress_image_ground_connection_subset:
_ecostress_image_ground_connection_subset.EcostressTimeTable_swigregister(EcostressTimeTable)
class EcostressTimeTableSubset(EcostressTimeTable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, Tt, Start_sample, Number_sample):
        _ecostress_image_ground_connection_subset.EcostressTimeTableSubset_swiginit(self, _ecostress_image_ground_connection_subset.new_EcostressTimeTableSubset(Tt, Start_sample, Number_sample))
    _v_start_sample = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressTimeTableSubset__v_start_sample)

    @property
    def start_sample(self):
        return self._v_start_sample()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _ecostress_image_ground_connection_subset.delete_EcostressTimeTableSubset

# Register EcostressTimeTableSubset in _ecostress_image_ground_connection_subset:
_ecostress_image_ground_connection_subset.EcostressTimeTableSubset_swigregister(EcostressTimeTableSubset)

__all__ = ["EcostressTimeTable","EcostressTimeTableSubset"]

class EcostressImageGroundConnectionSubset(geocal_swig.image_ground_connection.ImageGroundConnection):
    r"""

    This is a subset of the EcostressImageGroundConnection, with fewer
    samples.

    We needed this for a particular investigation (white paper for Landsat
    fill in), but go ahead and leave this in place for future use.

    C++ includes: ecostress_image_ground_connection_subset.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, Igc, Start_sample, Num_sample):
        r"""

        Ecostress::EcostressImageGroundConnectionSubset::EcostressImageGroundConnectionSubset(const boost::shared_ptr< EcostressImageGroundConnection > &Igc, int
        Start_sample, int Num_sample)
        Ecostress::EcostressImageGroundConnectionSubset::EcostressImageGroundC
        onnectionSubset
        """
        _ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset_swiginit(self, _ecostress_image_ground_connection_subset.new_EcostressImageGroundConnectionSubset(Igc, Start_sample, Num_sample))
    orbit_data = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset_orbit_data)
    scan_index_to_line = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset_scan_index_to_line)
    _v_crosses_dateline = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_crosses_dateline)

    @property
    def crosses_dateline(self):
        return self._v_crosses_dateline()

    _v_number_line_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_number_line_scan)

    @property
    def number_line_scan(self):
        return self._v_number_line_scan()

    _v_number_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_number_scan)

    @property
    def number_scan(self):
        return self._v_number_scan()

    _v_number_good_scan = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_number_good_scan)

    @property
    def number_good_scan(self):
        return self._v_number_good_scan()

    _v_underlying_igc = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_underlying_igc)

    @property
    def underlying_igc(self):
        return self._v_underlying_igc()

    _v_start_sample = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_start_sample)

    @property
    def start_sample(self):
        return self._v_start_sample()

    _v_camera = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_camera)

    @property
    def camera(self):
        return self._v_camera()

    _v_orbit = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_orbit)

    @property
    def orbit(self):
        return self._v_orbit()

    _v_sub_time_table = _swig_new_instance_method(_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset__v_sub_time_table)

    @property
    def sub_time_table(self):
        return self._v_sub_time_table()


    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _ecostress_image_ground_connection_subset.delete_EcostressImageGroundConnectionSubset

# Register EcostressImageGroundConnectionSubset in _ecostress_image_ground_connection_subset:
_ecostress_image_ground_connection_subset.EcostressImageGroundConnectionSubset_swigregister(EcostressImageGroundConnectionSubset)

__all__ = ["EcostressImageGroundConnectionSubset"]


