/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_hdfeos_filehandle_WRAP_H_
#define SWIG_hdfeos_filehandle_WRAP_H_

#include <map>
#include <string>


#endif
