# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
from ._swig_wrap import _simulated_radiance

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _simulated_radiance.SWIG_PyInstanceMethod_New
_swig_new_static_method = _simulated_radiance.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SWIG_MODULE_ALREADY_DONE = _simulated_radiance.SWIG_MODULE_ALREADY_DONE
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _simulated_radiance.delete_SwigPyIterator
    value = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_value)
    incr = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_copy)
    next = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_simulated_radiance.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_simulated_radiance.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _simulated_radiance:
_simulated_radiance.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _simulated_radiance.SHARED_PTR_DISOWN

import os

def _new_from_init(cls, version, *args):
    '''For use with pickle, covers common case where we just store the
    arguments needed to create an object. See for example HdfFile'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__(*args)
    return inst

def _new_from_serialization(data):
    return geocal_swig.serialize_function.serialize_read_binary(data)

def _new_from_serialization_dir(dir, data):
    curdir = os.getcwd()
    try:
      os.chdir(dir)
      return geocal_swig.serialize_function.serialize_read_binary(data)
    finally:
      os.chdir(curdir)


def _new_vector(cls, version, lst):
    '''Create a vector from a list.'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    for i in lst:
       inst.append(i)
    return inst

def _new_from_set(cls, version, *args):
    '''For use with pickle, covers common case where we use a set function 
    to assign the value'''
    if(cls.pickle_format_version() != version):
      raise RuntimeException("Class is expecting a pickled object with version number %d, but we found %d" % (cls.pickle_format_version(), version))
    inst = cls.__new__(cls)
    inst.__init__()
    inst.set(*args)
    return inst

import geocal_swig.generic_object
import geocal_swig.image_ground_connection
import geocal_swig.with_parameter
import geocal_swig.geocal_exception
import geocal_swig.observer
import geocal_swig.raster_image_variable
import geocal_swig.dem_map_info
class SimulatedRadiance(geocal_swig.generic_object.GenericObject):
    r"""

    This is used to produce simulated radiance data.

    This is based on an underlying Map_projected_image (e.g., ASTER data),
    and we simulate what ecostress would see when viewing this data. The
    simulated data is like L1A_PIX data, except that it is still in
    whatever units the Map_projected_image is. A separate step is needed
    to convert this into DNs to make a proper L1A_PIX file.

    C++ includes: simulated_radiance.h 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, Gca, Map_projected_image, Avg_fact=-1, Read_into_memory=False, Fill_value=0.0):
        r"""

        Ecostress::SimulatedRadiance::SimulatedRadiance(const boost::shared_ptr< GroundCoordinateArray > &Gca, const
        boost::shared_ptr< GeoCal::RasterImage > &Map_projected_image, int
        Avg_fact=-1, bool Read_into_memory=false, double Fill_value=0.0)
        Ecostress::SimulatedRadiance::SimulatedRadiance
        """
        _simulated_radiance.SimulatedRadiance_swiginit(self, _simulated_radiance.new_SimulatedRadiance(Gca, Map_projected_image, Avg_fact, Read_into_memory, Fill_value))
    radiance_scan = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance_radiance_scan)
    _v_ground_coordinate_array = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance__v_ground_coordinate_array)

    @property
    def ground_coordinate_array(self):
        return self._v_ground_coordinate_array()

    _v_avg_factor = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance__v_avg_factor)

    @property
    def avg_factor(self):
        return self._v_avg_factor()

    _v_fill_value = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance__v_fill_value)

    @property
    def fill_value(self):
        return self._v_fill_value()

    _v_read_into_memory = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance__v_read_into_memory)

    @property
    def read_into_memory(self):
        return self._v_read_into_memory()

    _v_map_projected_image = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance__v_map_projected_image)

    @property
    def map_projected_image(self):
        return self._v_map_projected_image()

    __str__ = _swig_new_instance_method(_simulated_radiance.SimulatedRadiance___str__)

    def __reduce__(self):
    #Special handling for when we are doing boost serialization, we set
    #"this" to None
      if(self.this is None):
        return super().__reduce__()
      return _new_from_serialization, (geocal_swig.serialize_function.serialize_write_binary(self),)

    __swig_destroy__ = _simulated_radiance.delete_SimulatedRadiance

# Register SimulatedRadiance in _simulated_radiance:
_simulated_radiance.SimulatedRadiance_swigregister(SimulatedRadiance)

__all__ = ["SimulatedRadiance"]


