#! /usr/bin/env python
#
# This runs the L1C process.
import warnings

# Have a warning message that we can't do anything about - suppress it
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=UserWarning)
    import geocal
import ecostress
import os
from multiprocessing import Pool
from loguru import logger
from pathlib import Path

# Get version information, in the top directory
import sys

sys.path.append(os.path.dirname(os.path.abspath(sys.path[0])))
from ecostress_version import pge_version, build_id, collection_label

version = "1.0"
usage = """Usage:
  l1c_process [options] <run_config>
  l1c_process [options] <l1b_rad> <l1b_geo> <osp_dir> <prod_dir>
  l1c_process -h | --help
  l1c_process -v | --version

This runs the L1C process.

Options:
  -h --help         
       Print this message

  --number-cpu=d
       Number of CPUs to use when processing. Ignored if we are using a 
       run_config file, this is instead passed through the config file.
       [default: 10]

  --verbose
       Print more information as we run to stderr.

  -v --version      
       Print program version
"""

args = geocal.docopt_simple(usage, version=version)

if args.run_config:
    config = ecostress.RunConfig(args.run_config)
    dem = ecostress.create_dem(config)
    lwm = ecostress.create_lwm(config)
    l1_osp_dir = Path(config["StaticAncillaryFileGroup", "L1_OSP_DIR"]).absolute()
else:
    config = None
    l1_osp_dir = Path(args.osp_dir).absolute()
    dem = geocal.SrtmDem(
        os.environ["ELEV_ROOT"],
        False,
        geocal.DatumGeoid96(os.environ["AFIDS_VDEV_DATA"] + "/EGM96_20_x100.HLF"),
    )
    if os.path.exists("/raid25/SRTM_2014_update/srtm_v3_lwm"):
        lwm = geocal.SrtmLwmData("/raid25/SRTM_2014_update/srtm_v3_lwm", False)
    elif os.path.exists("/project/ancillary/SRTM/srtm_v3_lwm"):
        lwm = geocal.SrtmLwmData("/project/ancillary/SRTM/srtm_v3_lwm", False)
    else:
        raise RuntimeError("Can't find land/water mask data")

# Read in additional configuration parameters
sys.path.append(str(l1_osp_dir))
import l1c_config

logger.remove()
if args.verbose:
    logger.add(sys.stderr, level="DEBUG")
else:
    logger.add(sys.stderr, level="INFO")

if args.run_config:
    ncpu = int(config["Process", "NumberCpu"])
    dirname = config["ProductPathGroup", "ProductPath"]
    file_version = config["ProductPathGroup", "ProductCounter"]
    l1b_rad_fname = os.path.abspath(config["InputFileGroup", "L1B_RAD"])
    l1b_geo_fname = os.path.abspath(config["InputFileGroup", "L1B_GEO"])
    build_id = config["PrimaryExecutable", "BuildID"]
    collection_label = config["ProductPathGroup", "CollectionLabel"]
else:
    ncpu = args.number_cpu
    dirname = os.path.abspath(args.prod_dir)
    file_version = "01"
    l1b_rad_fname = os.path.abspath(args.l1b_rad)
    l1b_geo_fname = os.path.abspath(args.l1b_geo)

orbit, scene, acquisition_time = ecostress.orbit_from_metadata(l1b_rad_fname)

geocal.makedirs_p(dirname)
os.chdir(dirname)

ofile = ecostress.ecostress_file_name(
    "L1CG_RAD",
    orbit,
    scene,
    acquisition_time,
    collection_label=collection_label,
    build=build_id,
    version=file_version,
)
ofile2 = ecostress.ecostress_file_name(
    "L1CT_RAD",
    orbit,
    scene,
    acquisition_time,
    collection_label=collection_label,
    build=build_id,
    version=file_version,
    tile=True,
    extension="",
)
logger.add(os.path.splitext(ofile)[0] + ".log", level="DEBUG")

pool = None
try:
    with logger.catch(reraise=True):
        inlist = [l1b_geo_fname, l1b_rad_fname, str(l1_osp_dir / "l1c_config.py")]
        l1cg = ecostress.L1cgGenerate(
            l1b_geo_fname,
            l1b_rad_fname,
            dem,
            lwm,
            ofile,
            inlist,
            resolution=l1c_config.l1cg_resolution,
            number_subpixel=l1c_config.l1cg_number_subpixel,
            run_config=config,
            collection_label=collection_label,
            build_id=build_id,
            pge_version=pge_version["l1c"],
            browse_band_list_5band=l1c_config.browse_band_list_5band,
            browse_band_list_3band=l1c_config.browse_band_list_3band,
            browse_size=l1c_config.l1cg_browse_size,
        )
        l1cg.run()
        l1ct = ecostress.L1ctGenerate(
            l1b_geo_fname,
            l1b_rad_fname,
            lwm,
            l1_osp_dir,
            ofile2,
            inlist,
            resolution=l1c_config.l1ct_resolution,
            number_subpixel=l1c_config.l1ct_number_subpixel,
            run_config=config,
            collection_label=collection_label,
            build_id=build_id,
            pge_version=pge_version["l1c"],
            browse_band_list_5band=l1c_config.browse_band_list_5band,
            browse_band_list_3band=l1c_config.browse_band_list_3band,
            browse_size=l1c_config.l1ct_browse_size,
        )
        if ncpu > 1:
            pool = Pool(ncpu)
        l1ct.run(pool=pool)
        pool.close()
except Exception:
    logger.info("L1C_PGE:ERROR-2-[Unexpected Error]")
    if pool is not None:
        pool.close()
    raise
except:
    logger.info("L1C_PGE:ERROR-2-[Unexpected Error]")
    if pool is not None:
        pool.close()
    raise
